# Importing the Necesary Files

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [5]:
import joblib

# Importing the dataset

In [6]:
data = pd.read_csv("heart_attack_prediction_dataset.csv")

In [7]:
data.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [8]:
data = data.drop(
    columns=['Patient ID','Cholesterol','Blood Pressure','Heart Rate','Income','Triglycerides','Country','Continent','Hemisphere']
    )

data.head()

,Age,Sex,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,Male,0,0,1,0,0,4.168189,Average,0,0,9,6.615001,31.251233,0,6,0
1,21,Male,1,1,1,1,1,1.813242,Unhealthy,1,0,1,4.963459,27.194973,1,7,0
2,21,Female,1,0,0,0,0,2.078353,Healthy,1,1,9,9.463426,28.176571,4,4,0
3,84,Male,1,1,1,0,1,9.828130,Average,1,0,9,7.648981,36.464704,3,4,0
4,66,Male,1,1,1,1,0,5.804299,Unhealthy,1,0,6,1.514821,21.809144,1,5,0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              8763 non-null   int64
 1   Sex                              8763 non-null   object
 2   Diabetes                         8763 non-null   int64
 3   Family History                   8763 non-null   int64
 4   Smoking                          8763 non-null   int64
 5   Obesity                          8763 non-null   int64
 6   Alcohol Consumption              8763 non-null   int64
 7   Exercise Hours Per Week          8763 non-null   float64
 8   Diet                             8763 non-null   object
 9   Previous Heart Problems          8763 non-null   int64
 10  Medication Use                   8763 non-null   int64
 11  Stress Level                     8763 non-null   int64
 12  Sedentary Hours Per Day          8763 non-null   float64
 13  BMI                              8763 non-null   float64
 14  Physical Activity Days Per Week  8763 non-null   int64
 15  Sleep Hours Per Day              8763 non-null   int64
 16  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(12), object(2)
memory usage: 1.1+ MB

In [10]:
data.describe()

,Age,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
count,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000
mean,53.707977,0.652288,0.492982,0.896839,0.501426,0.598083,10.014284,0.495835,0.498345,5.469702,5.993690,28.891446,3.489672,7.023508,0.358211
std,21.249509,0.476271,0.499979,0.304186,0.500026,0.490313,5.783745,0.500011,0.500026,2.859622,3.466359,6.319181,2.282687,1.988473,0.479502
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002442,0.000000,0.000000,1.000000,0.001263,18.002337,0.000000,4.000000,0.000000
25%,35.000000,0.000000,0.000000,1.000000,0.000000,0.000000,4.981579,0.000000,0.000000,3.000000,2.998794,23.422985,2.000000,5.000000,0.000000
50%,54.000000,1.000000,0.000000,1.000000,1.000000,1.000000,10.069559,0.000000,0.000000,5.000000,5.933622,28.768999,3.000000,7.000000,0.000000
75%,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.050018,1.000000,1.000000,8.000000,9.019124,34.324594,5.000000,9.000000,1.000000
max,90.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.998709,1.000000,1.000000,10.000000,11.999313,39.997211,7.000000,10.000000,1.000000

In [11]:
# Separate features and target
X = data.drop('Heart Attack Risk', axis=1)
y = data['Heart Attack Risk']

In [12]:
# One-hot encode categorical variables
X = pd.get_dummies(X, columns=['Sex', 'Diet'], drop_first=True)

In [13]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [14]:
# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [16]:
# predict_proba gives probability for both classes [0, 1]
probabilities = model.predict_proba(X_test)

# probability of heart attack risk = class 1
risk_prob = probabilities[:, 1]

In [17]:
print(risk_prob*100)

[35.47994036 38.07080269 34.93063129 ... 35.92940825 37.30900205
 38.28709437]

In [18]:
def predict_risk_probability(user_input_dict):
    """
    user_input_dict: dictionary of user features
    returns probability of heart risk (0–1)
    """
    user_df = pd.DataFrame([user_input_dict])

    # encode
    user_df = pd.get_dummies(user_df)

    # align columns with training data
    user_df = user_df.reindex(columns=X.columns, fill_value=0)

    # probability of class 1
    prob = model.predict_proba(user_df)[0][1]

    return prob

In [ ]:
user = {
    "Age": 23,
    "Sex": "Male",
    "Smoking": 1,
    "Alcohol Consumption": "Moderate",
    "Sleep Hours Per Day": 5,
    "Exercise Hours Per Week": 1,
    "Sedentary Hours Per Day": 9,
    "Stress Level": 8,
    "BMI": 27,
    "Diabetes": 0,
    "Family History": 1
}

prob = predict_risk_probability(user)
ans = prob*100
print(f"Estimated risk probability: {ans:.2f} %")

Estimated risk probability: 35.55 %

In [20]:
def predict_risk_probability(model, X_columns, user_input):
    user_df = pd.DataFrame([user_input])
    user_df = pd.get_dummies(user_df)
    user_df = user_df.reindex(columns=X_columns, fill_value=0)

    prob = model.predict_proba(user_df)[0][1]
    return prob

In [21]:
healthy_prob, healthy_drop = scenario_healthy_lifestyle(
    model, X.columns, user
)

print("If you improve sleep + quit smoking + stop alcohol:")
print(f"Old Probability:{prob*100:.2f}%")
print(f"New probability: {healthy_prob*100:.2f}%")
print(f"Estimated reduction: {healthy_drop*100:.1f}%")

NameError: name 'scenario_healthy_lifestyle' is not defined

In [22]:
joblib.dump(model,'model.pkl')

['model.pkl']